version: "3"

services:
  tadoku-web:
    image: tadoku/web:latest
    container_name: tadoku-web
    network_mode: bridge
    restart: always
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: tadoku.app
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: tadoku.app
      LETSENCRYPT_EMAIL: hello@tadoku.app
      API_ROOT: http://172.17.0.2:4000 # hardcoded for now, will revise infra hopefully before the end of the year
      GHOST_KEY: 22c9b1088957389622d210662f
      GHOST_URL: https://blog.tadoku.app
      SESSION_COOKIE_NAME: session_token
